import type { Metadata } from 'next'

import Header from '@/components/layout/header'

export const metadata: Metadata = {
  title: 'Scribly',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: React.ReactNode
  modal: React.ReactNode
}

export default function RootLayout({ children, modal }: LayoutProps) {
  return (
    <>
      <Header />
      <main className="min-h-main">{children}</main>
      {modal}
    </>
  )
}
