import type { Metadata } from 'next'
import { GeistSans } from 'geist/font'

import '@/styles/globals.css'
import Providers from '@/providers'

export const metadata: Metadata = {
  title: 'Scribly',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: React.ReactNode
  modal: React.ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
